variables:
  THREADS: 9

before_script:
  # workaround for docker permissions
  - sudo chown ghc:ghc -R .

  - sed -i -e 's%url *= *\.\./%url = https://git.haskell.org/%' .gitmodules
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git checkout .gitmodules

  - make clean || true
  - ./boot
  - ./configure

validate:
  image: ghcci/x86_64-linux-deb9:0.2
  script:
    - |
      echo 'HADDOCK_DOCS       = NO' >> mk/build.mk
      echo 'BUILD_SPHINX_HTML  = NO' >> mk/build.mk
      echo 'BUILD_SPHINX_PDF   = NO' >> mk/build.mk
    - |
      make V=0 -j$THREADS HADDOCK_DOCS=NO
    # posix009 is broken in nonmoving_thr
    - |
      make slowtest WAY="nonmoving nonmoving_thr" THREADS=$THREADS SKIP_PERF_TESTS=YES SKIP_TESTS="posix009 hpc_raytrace"
    - |
      make V=0 HADDOCK_DOCS=YES EXTRA_HADDOCK_OPTS="+RTS -xn -RTS"
